import { StylesType } from "../../theme/type";

const styles: StylesType<"root" | "features" | "images"> = {
  root: {
    label: "infoBox",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: ({ palette }) => palette.primary.light,
    margin: 2,
  },
  chooseUs: {
    label: "chooseUs",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "36px",
    lineHeight: "120.5%",
    letterSpacing: "0.031em",
    color: ({ palette }) => palette.primary.dark,
  },
  mainTitle: {
    label: "mainTitle",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "105px",
    lineHeight: "120.5%",
    letterSpacing: "0.033em",
    color: ({ palette }) => palette.primary.dark,
    ".underlineRed": {
      borderBottom: ({ palette }) => `8px solid ${palette.error.main}`,
      pb: "10px",
      display: "inline-block",
    },
  },
  images: {
    label: "images",
    display: "flex",
    gap: 2,
    mr: "149px",
    mt: "38px",
  },
  description: {
    label: "description",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "24px",
    lineHeight: "120.5%",
    letterSpacing: "0.031em",
    maxWidth: "1084px",
    color: ({ palette }) => palette.primary.dark,
    mt: "77px",
  },
  features: {
    label: "features",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    mx: "149px",
    maxWidth: "1084px",
    my: "35px",
  },
  feature: {
    label: "feature",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 3,
    img: {
      width: 48,
      height: 48,
    },
    p: {
      maxWidth: "264px",
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: 300,
      fontSize: "20px",
      lineHeight: "97%",
      letterSpacing: "0.031em",
      color: ({ palette }) => palette.primary.dark,
    },
  },
  slogan: {
    label: "slogan",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "70px",
    lineHeight: "120.5%",
    letterSpacing: "0.033em",
    color: ({ palette }) => palette.primary.dark,
    mt: "82px",
    ".textRed": {
      color: ({ palette }) => palette.error.main,
    },
  },
  newsLetter: {
    label: "newsLetter",
    boxShadow: "-1px 1px 9px rgba(0, 0, 0, 0.25)",
    borderRadius: "30px",
    mx: "20px",
    width: "90%",
    pl: "42px",
    mt: "86px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    ".newsLetterImage": {
      width: "566px",
      height: "293px",
      borderRadius: "30px",
    },
  },
  newsLetterText: {
    label: "newsLetterText",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "45.7709px",
    lineHeight: "108%",
    letterSpacing: "-0.027em",
    maxWidth: "616px",
    color: ({ palette }) => palette.primary.dark,
    ".textRed": {
      color: ({ palette }) => palette.error.main,
    },
  },
  inputGroup: {
    display: "flex",
    justifyContent: "center",
    alignItems: "enter",
    gap: 1,
    mt: "28px",
  },
  emailInput: {
    // "& .MuiInputBase-input": {
    //   backgroundColor: ({ palette }) => palette.common.white,
    //   maxWidth: "650px",
    //   border: "1px solid #000000",
    //   borderRadius: "20px",
    // },
  },
  sendButton: {
    backgroundColor: ({ palette }) => palette.primary.main,
    lineHeight: 1,
    width: "49px",
    height: "49px",
  },
};

export default styles;
