import { StylesType } from "../../theme/type";

const styles: StylesType<"root" | "features" | "images"> = {
  root: {
    label: "infoBox",
    backgroundColor: ({ palette }) => palette.primary.light,
    margin: 2,
  },
  container: {
    label: "infoBoxContainer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  chooseUs: {
    label: "chooseUs",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "36px",
    lineHeight: "120.5%",
    letterSpacing: "0.031em",
    color: ({ palette }) => palette.primary.dark,
  },
  mainTitle: {
    label: "mainTitle",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "105px",
    lineHeight: "120.5%",
    letterSpacing: "0.033em",
    color: ({ palette }) => palette.primary.dark,
    ".underlineRed": {
      borderBottom: ({ palette }) => `8px solid ${palette.error.main}`,
      pb: "10px",
      display: "inline-block",
    },
  },
  images: {
    label: "images",
    display: "flex",
    justifyContent: "center",
    gap: 2,
    mt: "38px",
    overflow: "hidden",
    img: {
      flex: "1 1 calc(33.3333% - 16px)",
      borderRadius: "10px",
    },
  },
  description: {
    label: "description",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "24px",
    lineHeight: "120.5%",
    letterSpacing: "0.031em",
    maxWidth: "1084px",
    color: ({ palette }) => palette.primary.dark,
    mt: "77px",
  },
  features: {
    label: "features",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    mx: "149px",
    maxWidth: "1084px",
    my: "35px",
  },
  feature: {
    label: "feature",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 3,
    img: {
      width: 48,
      height: 48,
    },
    p: {
      maxWidth: "264px",
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: 300,
      fontSize: "20px",
      lineHeight: "97%",
      letterSpacing: "0.031em",
      color: ({ palette }) => palette.primary.dark,
    },
  },
  slogan: {
    label: "slogan",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "70px",
    lineHeight: "120.5%",
    letterSpacing: "0.033em",
    color: ({ palette }) => palette.primary.dark,
    mt: "82px",
    ".textRed": {
      color: ({ palette }) => palette.error.main,
    },
  },
};

export default styles;
